---
geometry:
  - margin=0.75in
  - letterpaper
papersize: a4
author: "Frederic zur Bonsen (fzurbonsen@ethz.ch)"
date: "01.2026"
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{lastpage}
  \pagestyle{fancy}
  \fancyhead[L]{Frederic zur Bonsen (fzurbonsen@ethz.ch)}
  \fancyhead[C]{}
  \fancyhead[R]{\thepage/\pageref{LastPage}}
  \fancyfoot[C]{}
---